title: samdouble
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samdouble.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  samdouble

# Languages / i18n
languages: ["fr", "en"]
exclude_from_localizations: ["docs"]
defaultLang: en
languageNames:
  en: English
  fr: Français

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projets:
    output: true
  projets_posts:
    output: true
  restaurants:
    output: true
  restaurants_posts:
    output: true
  trips:
    output: true
  trips_posts:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
