name: Checks

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        node-version: ['20.19.4', '22.12.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Validate content.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./src/schema.json
          INPUT_JSONS: ./src/content.json
      - name: Check file size
        uses: freenet-actions/check-file-size@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: public
          max_size: 1000
          fail_on_find: true
          post_comment: true
          ignored_files: |
            public/assets/2024/04/20240411_europe/itinerary.xcf
      #- name: Text analysis
      #  uses: samdouble/textlinter@feat/make-lib
      #  with:
      #    label: samdouble
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Audit
        run: |
          npm run audit -- --moderate=3 --high=6
      - name: Check for packages
        uses: samdouble/package-reputation-action@master
        with:
          language: node
      - name: Test
        run: |
          npm test
      # - name: Visual Regression Tests
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-0 libwebkit2gtk-4.0-37 libwoff1 libharfbuzz-icu0 \
      #       libgstreamer-plugins-base1.0-0 libgstreamer-gl1.0-0 libgstreamer1.0-0 \
      #       libegl1 libopus0 libxslt1.1 libgstreamer-plugins-bad1.0-0 \
      #       libgstreamer-plugins-good1.0-0 libvpx7 libenchant-2-2 libsecret-1-0 \
      #       libhyphen0 libmanette-0.2-0
      #     npx playwright install
      #     npm run test-visual
      # - name: Upload screenshots
      #   uses: actions/upload-artifact@v4
      #   if: failure()
      #   with:
      #     name: playwright-snapshots
      #     path: test-results
      - name: Build
        run: |
          npm run build
