name: Checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Audit
        run: |
          npm run audit -- --moderate=2 --high=6
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
