name: Content Checks

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    strategy:
      matrix:
        os: ['ubuntu-24.04']
        node-version: ['22.12.0', '24.11.0']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Validate content.json schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./src/schema.json
          INPUT_JSONS: ./src/content.json
      - name: Validate content paths
        run: node scripts/validate-content-paths.js
      - name: Check file size
        uses: freenet-actions/check-file-size@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: public
          max_size: 1000
          fail_on_find: true
          post_comment: true
          ignored_files: |
            public/assets/2024/04/20240411_europe/itinerary.xcf
      #- name: Text analysis
      #  uses: samdouble/textlinter@feat/make-lib
      #  with:
      #    label: samdouble
