name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
      - name: Install
        run: |
          npm install
      - name: Deploy with gh-pages
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://git:${PAT}@github.com/samdouble/samdouble.github.io.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
